spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:C:/Users/Maciej.Pytka/git/ToDoApp/ToDoApp/ToDoDb'
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create
