spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
#    url: 'jdbc:h2:C:/Users/Maciej.Pytka/git/ToDoApp/ToDoApp/ToDoDb'
    url: 'jdbc:h2:C:/Users/Pyton/git/ToDoApp_SpringBoot/ToDoApp/toDoDb'
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create
my.prop: 'profile:local'