spring:
  flyway:
    baseline-on-migrate: true
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:C:/Users/Maciej.Pytka/git/ToDoApp_SpringBoot/ToDoApp/ToDoDb'
 #   url: 'jdbc:h2:C:/Users/Pyton/git/ToDoApp_SpringBoot/ToDoApp/toDoDb'
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
my.prop: 'profile:local'